apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: darkwing
  labels:
    app: darkwing-api
spec:
  type: NodePort
  selector:
    app: darkwing-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080
